#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_DIR="${ROOT_DIR}/skills/ops-basic/scripts"

disk_result="$(bash "${SCRIPT_DIR}/disk-hotspots.sh" '{"path":"/var","top_n":3}')"
resource_result="$(bash "${SCRIPT_DIR}/resource-inspect.sh" '{"top_n":3}')"
process_result="$(bash "${SCRIPT_DIR}/process-inspect.sh" '{"pattern":"systemd"}')"
cleanup_result="$(bash "${SCRIPT_DIR}/safe-log-cleanup.sh" '{"path":"/etc/passwd","dry_run":true}')"
cleanup_plan_result="$(bash "${SCRIPT_DIR}/log-cleanup-plan.sh" '{"root_path":"/etc","min_size_mb":1}')"
cleanup_plan_bad_number="$(bash "${SCRIPT_DIR}/log-cleanup-plan.sh" '{"root_path":"/tmp","min_size_mb":"abc"}')"
restart_plan_result="$(bash "${SCRIPT_DIR}/service-restart-plan.sh" '{"service":"sshd"}')"
log_search_reject="$(bash "${SCRIPT_DIR}/log-search.sh" "{\"path\":\"${ROOT_DIR}/README.md\",\"keyword\":\"Linux\",\"lines\":1}")"
log_search_no_journal="$(bash "${SCRIPT_DIR}/log-search.sh" '{"path":"/var/log","keyword":"__unlikely_linux_agent_test_keyword__","lines":1,"include_journal":false}')"

cleanup_file="$(mktemp /tmp/linux-agent-tools-cleanup.XXXXXX)"
printf '0123456789' > "${cleanup_file}"
cleanup_false_result="$(bash "${SCRIPT_DIR}/safe-log-cleanup.sh" "$(jq -cn --arg path "${cleanup_file}" '{path:$path, max_size_mb:0, dry_run:false}')")"
cleanup_false_size="$(stat -c '%s' "${cleanup_file}")"
rm -f "${cleanup_file}"

cleanup_bad_number_file="$(mktemp /tmp/linux-agent-tools-bad-number.XXXXXX)"
printf 'data' > "${cleanup_bad_number_file}"
cleanup_bad_number_result="$(bash "${SCRIPT_DIR}/safe-log-cleanup.sh" "$(jq -cn --arg path "${cleanup_bad_number_file}" '{path:$path, max_size_mb:"abc"}')")"
rm -f "${cleanup_bad_number_file}"

cleanup_target="$(mktemp /tmp/linux-agent-tools-target.XXXXXX)"
cleanup_link="$(mktemp -u /tmp/linux-agent-tools-link.XXXXXX)"
printf 'keep-me' > "${cleanup_target}"
ln -s "${cleanup_target}" "${cleanup_link}"
cleanup_symlink_result="$(bash "${SCRIPT_DIR}/safe-log-cleanup.sh" "$(jq -cn --arg path "${cleanup_link}" '{path:$path, max_size_mb:0, dry_run:false}')")"
cleanup_target_size="$(stat -c '%s' "${cleanup_target}")"
rm -f "${cleanup_link}" "${cleanup_target}"

tmp_link="$(mktemp -u)"
ln -s "${ROOT_DIR}/README.md" "${tmp_link}"
log_search_symlink="$(bash "${SCRIPT_DIR}/log-search.sh" "{\"path\":\"${tmp_link}\",\"keyword\":\"Linux\",\"lines\":1}")"
rm -f "${tmp_link}"

grep -q '"ok": true' <<<"$(jq . <<<"${disk_result}")"
grep -q '"tool": "system.resource.inspect"' <<<"$(jq . <<<"${resource_result}")"
grep -q '"tool": "system.process.inspect"' <<<"$(jq . <<<"${process_result}")"
grep -q '"ok": false' <<<"$(jq . <<<"${cleanup_result}")"
grep -q '"tool": "system.logs.cleanup_plan"' <<<"$(jq . <<<"${cleanup_plan_result}")"
grep -q '"ok": false' <<<"$(jq . <<<"${cleanup_plan_result}")"
grep -q '"ok": false' <<<"$(jq . <<<"${cleanup_plan_bad_number}")"
grep -q 'min_size_mb 必须是正整数' <<<"${cleanup_plan_bad_number}"
grep -q '"action": "truncate"' <<<"$(jq . <<<"${cleanup_false_result}")"
[[ "${cleanup_false_size}" -eq 0 ]]
grep -q '"ok": false' <<<"$(jq . <<<"${cleanup_bad_number_result}")"
grep -q 'max_size_mb 必须是非负整数' <<<"${cleanup_bad_number_result}"
grep -q '"ok": false' <<<"$(jq . <<<"${cleanup_symlink_result}")"
grep -q '拒绝清理符号链接' <<<"${cleanup_symlink_result}"
[[ "${cleanup_target_size}" -gt 0 ]]
grep -q '"risk": "high"' <<<"$(jq . <<<"${restart_plan_result}")"
grep -q '"ok": false' <<<"$(jq . <<<"${log_search_reject}")"
grep -q '仅允许检索 /var/log' <<<"${log_search_reject}"
grep -q '"ok": false' <<<"$(jq . <<<"${log_search_symlink}")"
grep -q '"include_journal": false' <<<"$(jq . <<<"${log_search_no_journal}")"
grep -q '"journal_sample": ""' <<<"$(jq . <<<"${log_search_no_journal}")"

source "${ROOT_DIR}/lib/common.sh"
source "${ROOT_DIR}/lib/config.sh"
source "${ROOT_DIR}/lib/policy.sh"
source "${ROOT_DIR}/lib/skills.sh"
source "${ROOT_DIR}/lib/doctor.sh"
linux_agent_init_env "${ROOT_DIR}"
linux_agent_load_config
doctor_json="$(linux_agent_doctor)"
grep -q '"skills_ok": true' <<<"$(jq . <<<"${doctor_json}")"
skills_json="$(linux_agent_validate_skills)"
grep -q '"ok": true' <<<"$(jq . <<<"${skills_json}")"
resource_skill_result="$(linux_agent_run_skill_script ops-basic/resource-inspect '{"top_n":3}')"
resource_skill_string_arg_result="$(linux_agent_run_skill_script ops-basic/resource-inspect "$(jq -cn --arg args '{"top_n":2}' '$args')")"
process_skill_result="$(linux_agent_run_skill_script ops-basic/process-inspect '{"pattern":"systemd"}')"
grep -q '"tool": "system.resource.inspect"' <<<"$(jq . <<<"${resource_skill_result}")"
grep -q '"tool": "system.resource.inspect"' <<<"$(jq . <<<"${resource_skill_string_arg_result}")"
grep -q '"tool": "system.process.inspect"' <<<"$(jq . <<<"${process_skill_result}")"

broken_skills_root="$(mktemp -d)"
cp -a "${ROOT_DIR}/skills" "${broken_skills_root}/skills"
printf '\n- `ops-basic/ghost-script`: bogus\n' >> "${broken_skills_root}/skills/INDEX.md"
printf '\n- `scripts/ghost-script.sh`: bogus\n' >> "${broken_skills_root}/skills/ops-basic/SKILL.md"
original_config_json="${LINUX_AGENT_CONFIG_JSON}"
LINUX_AGENT_CONFIG_JSON="$(jq --arg skills_dir "${broken_skills_root}/skills" '.skills_dir=$skills_dir' <<<"${LINUX_AGENT_CONFIG_JSON}")"
broken_skills_json="$(linux_agent_validate_skills)"
grep -q '"ok": false' <<<"$(jq . <<<"${broken_skills_json}")"
grep -q 'SKILL_SCRIPT_FILE_MISSING' <<<"${broken_skills_json}"
grep -q 'SKILL_INDEX_BROKEN_REF' <<<"${broken_skills_json}"
LINUX_AGENT_CONFIG_JSON="${original_config_json}"
rm -rf "${broken_skills_root}"

printf 'tools: ok\n'
