"""Process execution adapter for synchronous and background Web requests.

The service owns the complete child-process lifecycle: context/environment
injection, concurrent pipe draining, partial stderr publication, timeouts,
cancellation, process-group escalation, and reaping.  HTTP and Job lifecycle
code can therefore depend on one result envelope without manipulating
``subprocess.Popen`` directly.
"""

import json
import os
import select
import signal
import subprocess
import sys
import threading
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


DEFAULT_STDERR_TEXT_LIMIT = 4000
WORK_EXECUTION_FLOW_TEXT_LIMIT = 200000
DEFAULT_OUTPUT_BYTE_LIMIT = 1_048_576
API_KEY_ACTIONS = frozenset({("work", "run"), ("edit", "plan")})
LINUX_PARENT_DEATH_SUPERVISOR = "--linux-parent-death-supervisor"
PR_SET_PDEATHSIG = 1
POSIX_PROCESS_GROUPS = os.name == "posix" and hasattr(os, "killpg")


def _set_linux_parent_death_signal(signum):
    """Ask Linux to signal this process when its creating parent thread dies."""

    # ``preexec_fn`` is unsafe in the threaded Web server.  This helper runs in
    # a fresh interpreter instead, before it creates the actual Agent worker.
    import ctypes

    libc = ctypes.CDLL(None, use_errno=True)
    result = libc.prctl(
        PR_SET_PDEATHSIG,
        int(signum),
        0,
        0,
        0,
    )
    if result != 0:
        error_number = ctypes.get_errno()
        raise OSError(error_number, os.strerror(error_number))


def _parent_death_supervisor(expected_parent_pid, liveness_fd, command):
    """Keep an Agent process group bound to the lifetime of its Web parent."""

    try:
        expected_parent_pid = int(expected_parent_pid)
    except (TypeError, ValueError) as exc:
        raise ValueError("supervisor parent pid must be an integer") from exc
    try:
        liveness_fd = int(liveness_fd)
    except (TypeError, ValueError) as exc:
        raise ValueError("supervisor liveness fd must be an integer") from exc
    if expected_parent_pid <= 1 or liveness_fd < 0 or not command:
        raise ValueError("supervisor requires a live parent and a command")

    def terminate_process_group(_signum, _frame):
        # PDEATHSIG is delivered only to this direct child.  SIGKILL the whole
        # session so the Agent and any ordinary descendants cannot outlive it.
        os.killpg(os.getpgrp(), signal.SIGKILL)

    if sys.platform.startswith("linux"):
        signal.signal(signal.SIGUSR1, terminate_process_group)

    # The inherited read end provides durable parent identity without relying
    # on a persisted PID.  EOF is generated by the kernel even for SIGKILL.
    os.fstat(liveness_fd)
    if os.getppid() != expected_parent_pid:
        return 125
    if sys.platform.startswith("linux"):
        # A parent can die before or during prctl().  Checking on both sides
        # closes that race; the liveness pipe independently covers interpreter
        # startup before the signal handler exists.
        _set_linux_parent_death_signal(signal.SIGUSR1)
    if os.getppid() != expected_parent_pid:
        return 125

    worker = subprocess.Popen(command)
    while True:
        readable, _, _ = select.select((liveness_fd,), (), (), 0.1)
        if readable and os.read(liveness_fd, 1) == b"":
            terminate_process_group(signal.SIGKILL, None)
        returncode = worker.poll()
        if returncode is not None:
            break
    os.close(liveness_fd)
    if returncode < 0:
        return 128 + abs(returncode)
    return returncode


def _run_supervisor_from_argv(argv):
    if len(argv) < 5 or argv[1] != LINUX_PARENT_DEATH_SUPERVISOR:
        return None
    try:
        return _parent_death_supervisor(argv[2], argv[3], argv[4:])
    except Exception as exc:  # The outer execution envelope captures stderr.
        print(f"execution supervisor failed: {exc}", file=sys.stderr, flush=True)
        return 125


@dataclass(frozen=True)
class RequestContext:
    """Filesystem and identity scope injected into one Agent subprocess."""

    request_id: str
    session_id: str
    audit_log: Path
    history_file: Path
    job_id: str = ""
    tmp_dir: Optional[Path] = None

    def __post_init__(self):
        request_id = str(self.request_id or "")
        session_id = str(self.session_id or "")
        job_id = str(self.job_id or "")
        if not request_id:
            raise ValueError("request_id is required")
        if not session_id:
            raise ValueError("session_id is required")
        if job_id and self.tmp_dir is None:
            raise ValueError("a Job RequestContext requires tmp_dir")
        object.__setattr__(self, "request_id", request_id)
        object.__setattr__(self, "session_id", session_id)
        object.__setattr__(self, "job_id", job_id)
        object.__setattr__(self, "audit_log", Path(self.audit_log))
        object.__setattr__(self, "history_file", Path(self.history_file))
        if self.tmp_dir is not None:
            object.__setattr__(self, "tmp_dir", Path(self.tmp_dir))

    @property
    def is_job(self):
        return bool(self.job_id)


@dataclass(frozen=True)
class _ProcessOutcome:
    stdout: str
    stderr: str
    stdout_truncated_bytes: int
    stderr_truncated_bytes: int
    output_limit_exceeded: bool
    returncode: Optional[int]
    timed_out: bool
    cancelled: bool


class ExecutionService:
    """Run ``bash bin/agent api`` with bounded, observable process semantics."""

    def __init__(
        self,
        root,
        agent,
        env_builder,
        session_store,
        job_reader,
        partial_writer,
        workspace_lock,
        process_registry,
        process_registry_lock,
        cancel_grace=2,
        default_job_timeout=900,
        max_output_bytes=DEFAULT_OUTPUT_BYTE_LIMIT,
    ):
        if not callable(env_builder):
            raise TypeError("env_builder must be callable")
        if session_store is None or not callable(getattr(session_store, "current_paths", None)):
            raise TypeError("session_store must provide current_paths()")
        if job_reader is not None and not callable(job_reader):
            raise TypeError("job_reader must be callable")
        if partial_writer is not None and not callable(partial_writer):
            raise TypeError("partial_writer must be callable")

        self.root = Path(root)
        self.agent = Path(agent)
        self.env_builder = env_builder
        self.session_store = session_store
        self.job_reader = job_reader
        self.partial_writer = partial_writer
        self.workspace_lock = workspace_lock or threading.RLock()
        self.process_registry = process_registry if process_registry is not None else {}
        self.process_registry_lock = process_registry_lock or threading.Lock()
        self.cancel_grace = self._nonnegative_number(cancel_grace, "cancel_grace")
        self.default_job_timeout = self._positive_timeout(
            default_job_timeout,
            "default_job_timeout",
            allow_none=True,
        )
        try:
            output_limit = int(max_output_bytes)
        except (TypeError, ValueError) as exc:
            raise ValueError("max_output_bytes must be a positive integer") from exc
        if output_limit <= 0:
            raise ValueError("max_output_bytes must be a positive integer")
        self.max_output_bytes = output_limit
        self._termination_requests = set()

    @staticmethod
    def _nonnegative_number(value, name):
        if isinstance(value, bool):
            raise ValueError(f"{name} must be a non-negative number")
        try:
            normalized = float(value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{name} must be a non-negative number") from exc
        if normalized < 0:
            raise ValueError(f"{name} must be a non-negative number")
        return normalized

    @staticmethod
    def _positive_timeout(value, name="timeout", allow_none=False):
        if value is None and allow_none:
            return None
        if isinstance(value, bool):
            raise ValueError(f"{name} must be a positive number")
        try:
            normalized = float(value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{name} must be a positive number") from exc
        if normalized <= 0:
            raise ValueError(f"{name} must be a positive number")
        return normalized

    def workspace_context(self, request_id=None):
        paths = self.session_store.current_paths()
        return RequestContext(
            request_id=str(request_id or uuid.uuid4().hex),
            session_id=paths.session_id,
            audit_log=paths.audit_log,
            history_file=paths.history_file,
        )

    @staticmethod
    def job_context(context):
        if isinstance(context, RequestContext):
            if not context.is_job:
                raise ValueError("run_job requires a Job RequestContext")
            return context
        try:
            paths = context.private
            return RequestContext(
                request_id=context.request_id,
                job_id=context.job_id,
                session_id=paths.session_id,
                audit_log=paths.audit_log,
                history_file=paths.history_file,
                tmp_dir=context.private_tmp_dir,
            )
        except AttributeError as exc:
            raise TypeError(
                "Job context must be RequestContext or JobSessionContext-compatible"
            ) from exc

    def _command(self, resource, action, payload):
        command = ["bash", str(self.agent), "api", str(resource)]
        if action:
            command.append(str(action))
        command.append(
            json.dumps(
                {} if payload is None else payload,
                ensure_ascii=False,
                separators=(",", ":"),
                allow_nan=False,
            )
        )
        return command

    def _environment(self, resource, action, context):
        include_api_key = (str(resource), str(action or "")) in API_KEY_ACTIONS
        built = self.env_builder(include_api_key=include_api_key)
        try:
            env = dict(built)
        except (TypeError, ValueError) as exc:
            raise TypeError("env_builder must return a mapping") from exc

        # These values belong to RequestContext, never to ambient process state.
        env.pop("LINUX_AGENT_JOB_ID", None)
        env["LINUX_AGENT_SESSION_MANAGED_EXTERNALLY"] = "1"
        env["LINUX_AGENT_SESSION_ID"] = context.session_id
        env["LINUX_AGENT_AUDIT_LOG"] = str(context.audit_log)
        env["LINUX_AGENT_CONVERSATION_HISTORY_FILE"] = str(context.history_file)
        env["LINUX_AGENT_REQUEST_ID"] = context.request_id
        if context.is_job:
            env["LINUX_AGENT_JOB_ID"] = context.job_id
            env["TMPDIR"] = str(context.tmp_dir)
        return env

    def run_sync(
        self,
        resource,
        action="",
        payload=None,
        timeout=None,
        request_id=None,
    ):
        """Run against the active workspace while holding its lock."""

        normalized_timeout = (
            None
            if timeout is None
            else self._positive_timeout(timeout, "timeout", allow_none=False)
        )
        with self.workspace_lock:
            context = self.workspace_context(request_id=request_id)
            outcome = self._execute(
                self._command(resource, action, payload),
                self._environment(resource, action, context),
                context,
                str(resource),
                normalized_timeout,
            )
        return self._result_envelope(outcome, str(resource), normalized_timeout)

    def run_job(self, resource, action="", payload=None, context=None, timeout=None):
        """Run in a private Job context and register the process for cancellation."""

        request_context = self.job_context(context)
        normalized_timeout = self.default_job_timeout
        if timeout is not None:
            normalized_timeout = self._positive_timeout(timeout, "timeout", allow_none=False)
        outcome = self._execute(
            self._command(resource, action, payload),
            self._environment(resource, action, request_context),
            request_context,
            str(resource),
            normalized_timeout,
        )
        return self._result_envelope(outcome, str(resource), normalized_timeout)

    def run_external_sync(
        self,
        command,
        env,
        *,
        timeout,
        resource="external",
        request_id=None,
    ):
        """Run a trusted adapter command with the same bounded lifecycle."""

        if not isinstance(command, (list, tuple)) or not command:
            raise ValueError("command must be a non-empty sequence")
        if not all(isinstance(item, str) and item for item in command):
            raise ValueError("command items must be non-empty strings")
        try:
            normalized_env = dict(env)
        except (TypeError, ValueError) as exc:
            raise TypeError("env must be a mapping") from exc
        normalized_timeout = self._positive_timeout(
            timeout,
            "timeout",
            allow_none=False,
        )
        with self.workspace_lock:
            context = self.workspace_context(request_id=request_id)
            return self._execute(
                list(command),
                normalized_env,
                context,
                str(resource),
                normalized_timeout,
            )

    def _spawn(self, command, env):
        supervised_command = command
        liveness_fds = None
        popen_options = {}
        if POSIX_PROCESS_GROUPS:
            liveness_fds = os.pipe()
            read_fd, write_fd = liveness_fds
            supervised_command = [
                sys.executable,
                str(Path(__file__).resolve()),
                LINUX_PARENT_DEATH_SUPERVISOR,
                str(os.getpid()),
                str(read_fd),
                *command,
            ]
            popen_options["pass_fds"] = (read_fd,)
            popen_options["start_new_session"] = True
        try:
            process = subprocess.Popen(
                supervised_command,
                cwd=str(self.root),
                env=env,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                **popen_options,
            )
        except BaseException:
            if liveness_fds is not None:
                self._close_fd(liveness_fds[0])
                self._close_fd(liveness_fds[1])
            raise
        if liveness_fds is not None:
            self._close_fd(liveness_fds[0])
            process._linux_agent_liveness_fd = liveness_fds[1]
        return process

    @staticmethod
    def _close_fd(fd):
        try:
            os.close(fd)
        except OSError:
            pass

    @staticmethod
    def _close_liveness_pipe(process):
        liveness_fd = getattr(process, "_linux_agent_liveness_fd", None)
        if liveness_fd is None:
            return
        process._linux_agent_liveness_fd = None
        ExecutionService._close_fd(liveness_fd)

    def _abort_after_reader_start_failure(self, process, threads):
        """Bound process and pipe lifetime when a drain thread cannot start."""

        try:
            self._terminate_process(process)
        finally:
            for thread in threads:
                if thread.is_alive():
                    thread.join(timeout=max(1.0, self.cancel_grace + 1.0))
            if process.stdout is not None:
                process.stdout.close()
            if process.stderr is not None:
                process.stderr.close()

    def _register_process(self, context, process):
        should_run = True
        try:
            with self.process_registry_lock:
                if self.job_reader is not None:
                    job = self.job_reader(context.job_id)
                    should_run = bool(
                        isinstance(job, dict)
                        and job.get("status") == "running"
                        and not job.get("cancel_requested_at")
                    )
                if should_run:
                    if context.job_id in self.process_registry:
                        raise RuntimeError(
                            f"a process is already registered for Job {context.job_id}"
                        )
                    self.process_registry[context.job_id] = process
                    return True
        except BaseException:
            self._terminate_process(process)
            raise

        self._terminate_process(process)
        return False

    def _remove_registered_process(self, job_id, process):
        if not job_id:
            return False
        with self.process_registry_lock:
            if self.process_registry.get(job_id) is process:
                self.process_registry.pop(job_id, None)
            requested = job_id in self._termination_requests
            self._termination_requests.discard(job_id)
            return requested

    def _emit_partial(self, job_id, resource, stderr_text):
        if self.partial_writer is None or not job_id or not stderr_text:
            return
        self.partial_writer(job_id, resource, stderr_text)

    def _execute(self, command, env, context, resource, timeout):
        process = self._spawn(command, env)
        stdout_chunks = []
        stderr_chunks = []
        reader_errors = []
        last_partial_at = [0.0]
        last_partial_text = [""]
        stdout_total_bytes = [0]
        stderr_total_bytes = [0]
        output_limit_event = threading.Event()
        byte_limit = self.max_output_bytes

        def read_stdout():
            try:
                if process.stdout is None:
                    return
                read_chunk = getattr(process.stdout, "read1", process.stdout.read)
                while True:
                    chunk = read_chunk(65536)
                    if not chunk:
                        break
                    previous = stdout_total_bytes[0]
                    stdout_total_bytes[0] += len(chunk)
                    remaining = max(0, byte_limit - previous)
                    if remaining:
                        stdout_chunks.append(chunk[:remaining])
                    if len(chunk) > remaining:
                        output_limit_event.set()
            except Exception as exc:  # Drain failures are raised after cleanup.
                reader_errors.append(exc)

        def read_stderr():
            try:
                if process.stderr is None:
                    return
                read_chunk = getattr(process.stderr, "read1", process.stderr.read)
                while True:
                    chunk = read_chunk(65536)
                    if not chunk:
                        break
                    previous = stderr_total_bytes[0]
                    stderr_total_bytes[0] += len(chunk)
                    remaining = max(0, byte_limit - previous)
                    if remaining:
                        stderr_chunks.append(chunk[:remaining])
                    if len(chunk) > remaining:
                        output_limit_event.set()
                    now = time.monotonic()
                    if now - last_partial_at[0] < 0.25:
                        continue
                    text = b"".join(stderr_chunks).decode("utf-8", errors="replace").strip()
                    try:
                        self._emit_partial(context.job_id, resource, text)
                    except Exception as exc:
                        reader_errors.append(exc)
                    last_partial_text[0] = text
                    last_partial_at[0] = now
            except Exception as exc:  # Keep the process lifecycle bounded.
                reader_errors.append(exc)

        stdout_thread = threading.Thread(target=read_stdout, daemon=True)
        stderr_thread = threading.Thread(target=read_stderr, daemon=True)
        try:
            stdout_thread.start()
            stderr_thread.start()
        except BaseException:
            self._abort_after_reader_start_failure(
                process,
                (stdout_thread, stderr_thread),
            )
            raise

        registered = not context.is_job
        timed_out = False
        cancelled = False
        returncode = None
        execution_error = None
        try:
            if context.is_job:
                registered = self._register_process(context, process)
                if not registered:
                    cancelled = True
            if registered:
                deadline = None if timeout is None else time.monotonic() + timeout
                while returncode is None:
                    if output_limit_event.is_set():
                        termination = self._terminate_process(process)
                        returncode = termination["returncode"]
                        break
                    wait_timeout = 0.05
                    if deadline is not None:
                        remaining = deadline - time.monotonic()
                        if remaining <= 0:
                            timed_out = True
                            termination = self._terminate_process(process)
                            returncode = termination["returncode"]
                            break
                        wait_timeout = min(wait_timeout, remaining)
                    try:
                        returncode = process.wait(timeout=wait_timeout)
                    except subprocess.TimeoutExpired:
                        continue
            else:
                returncode = process.poll()
        except BaseException as exc:
            execution_error = exc
            if process.poll() is None:
                self._terminate_process(process)
            returncode = process.poll()
        finally:
            self._close_liveness_pipe(process)
            # The supervised worker may exit after spawning an ordinary child
            # that closes the inherited output pipes.  Once the direct child is
            # reaped, no process in its private group is allowed to outlive the
            # request lifecycle.
            if process.poll() is not None and self._process_group_exists(process.pid):
                self._kill_process_group(process.pid)
            join_timeout = max(1.0, self.cancel_grace + 1.0)
            stdout_thread.join(timeout=join_timeout)
            stderr_thread.join(timeout=join_timeout)
            if stdout_thread.is_alive() or stderr_thread.is_alive():
                self._kill_process_group(process.pid)
                stdout_thread.join(timeout=1.0)
                stderr_thread.join(timeout=1.0)
            if stdout_thread.is_alive() or stderr_thread.is_alive():
                reader_errors.append(RuntimeError("process output reader did not stop"))
            if process.stdout is not None and not stdout_thread.is_alive():
                process.stdout.close()
            if process.stderr is not None and not stderr_thread.is_alive():
                process.stderr.close()
            cancelled = (
                cancelled
                or self._remove_registered_process(context.job_id, process)
            )

        stdout = b"".join(stdout_chunks).decode("utf-8", errors="replace").strip()
        stderr = b"".join(stderr_chunks).decode("utf-8", errors="replace").strip()
        if stderr and stderr != last_partial_text[0]:
            try:
                self._emit_partial(context.job_id, resource, stderr)
            except Exception as exc:
                reader_errors.append(exc)
        if execution_error is not None:
            raise execution_error
        if reader_errors:
            raise reader_errors[0]
        stdout_truncated = max(0, stdout_total_bytes[0] - byte_limit)
        stderr_truncated = max(0, stderr_total_bytes[0] - byte_limit)
        output_limited = bool(stdout_truncated or stderr_truncated)
        if output_limited:
            notice = (
                f"[output capped at {byte_limit} bytes per stream; process terminated]"
            )
            stderr = (stderr + "\n" + notice).strip() if stderr else notice
        return _ProcessOutcome(
            stdout=stdout,
            stderr=stderr,
            stdout_truncated_bytes=stdout_truncated,
            stderr_truncated_bytes=stderr_truncated,
            output_limit_exceeded=output_limited,
            returncode=returncode,
            timed_out=timed_out,
            cancelled=cancelled,
        )

    @staticmethod
    def _signal_process_group(process, signum):
        if POSIX_PROCESS_GROUPS:
            try:
                os.killpg(process.pid, signum)
                return True
            except ProcessLookupError:
                return False
            except OSError:
                pass
        try:
            if signum == signal.SIGTERM:
                process.terminate()
            else:
                process.kill()
            return True
        except (OSError, ProcessLookupError):
            return False

    @staticmethod
    def _process_group_exists(pgid):
        if not POSIX_PROCESS_GROUPS:
            return False
        try:
            os.killpg(pgid, 0)
            return True
        except ProcessLookupError:
            return False
        except PermissionError:
            return True

    @classmethod
    def _kill_process_group(cls, pgid):
        if not POSIX_PROCESS_GROUPS:
            return False
        try:
            os.killpg(pgid, signal.SIGKILL)
            return True
        except (ProcessLookupError, PermissionError):
            return False

    def _terminate_process(self, process):
        term_sent = self._signal_process_group(process, signal.SIGTERM)
        returncode = process.poll()
        if returncode is None:
            try:
                returncode = process.wait(timeout=self.cancel_grace)
            except subprocess.TimeoutExpired:
                returncode = None

        killed = False
        if returncode is None or self._process_group_exists(process.pid):
            killed = self._signal_process_group(process, signal.SIGKILL)
        if returncode is None:
            # SIGKILL cannot be handled or ignored; wait unconditionally so the
            # direct child never remains a zombie after this method returns.
            returncode = process.wait()
        self._close_liveness_pipe(process)

        return {
            "term_sent": term_sent,
            "sigkill_sent": killed,
            "returncode": returncode,
            "reaped": process.poll() is not None,
        }

    def terminate(self, job_id):
        """Cancel and reap one registered Job process."""

        job_id = str(job_id)
        with self.process_registry_lock:
            process = self.process_registry.pop(job_id, None)
            if process is not None:
                self._termination_requests.add(job_id)
        if process is None:
            return {"ok": False, "status": "not_running", "job_id": job_id}
        result = self._terminate_process(process)
        return {"ok": True, "status": "terminated", "job_id": job_id, **result}

    def terminate_all(self):
        """Cancel and reap every registered Job process."""

        with self.process_registry_lock:
            processes = list(self.process_registry.items())
            self.process_registry.clear()
            self._termination_requests.update(job_id for job_id, _ in processes)
        results = []
        for job_id, process in processes:
            result = self._terminate_process(process)
            results.append(
                {"ok": True, "status": "terminated", "job_id": job_id, **result}
            )
        return {"ok": True, "status": "terminated_all", "results": results}

    @staticmethod
    def _limited_text(text, limit):
        raw = str(text or "").encode("utf-8", errors="replace")
        if limit <= 0:
            return "", len(raw)
        if len(raw) <= limit:
            return raw.decode("utf-8", errors="replace"), 0
        return raw[:limit].decode("utf-8", errors="replace"), len(raw) - limit

    @classmethod
    def _stderr_block(cls, resource, stderr, truncated_bytes=0):
        if not stderr:
            return None
        is_work = resource == "work"
        limit = (
            WORK_EXECUTION_FLOW_TEXT_LIMIT
            if is_work
            else DEFAULT_STDERR_TEXT_LIMIT
        )
        text, display_truncated = cls._limited_text(stderr, limit)
        return {
            "kind": "stdout" if is_work else "stderr",
            "title": "执行流程" if is_work else "Agent stderr",
            "text": text,
            "truncated_bytes": int(truncated_bytes) + display_truncated,
        }

    @classmethod
    def _result_envelope(cls, outcome, resource, timeout):
        if outcome.output_limit_exceeded:
            result = {
                "ok": False,
                "status": "output_limit_exceeded",
                "code": "output_limit_exceeded",
                "error": "Agent output exceeded execution.max_output_bytes and was terminated.",
                "timeline": [],
                "approval_card": None,
                "output_blocks": [],
            }
            if outcome.stdout:
                text, display_truncated = cls._limited_text(outcome.stdout, 4000)
                result["output_blocks"].append(
                    {
                        "kind": "stdout",
                        "title": "Agent stdout",
                        "text": text,
                        "truncated_bytes": outcome.stdout_truncated_bytes + display_truncated,
                    }
                )
        else:
            try:
                result = json.loads(outcome.stdout) if outcome.stdout else {}
            except json.JSONDecodeError:
                result = None
            if not isinstance(result, dict):
                text, display_truncated = cls._limited_text(outcome.stdout, 4000)
                result = {
                    "ok": False,
                    "status": "invalid_agent_output",
                    "timeline": [],
                    "approval_card": None,
                    "output_blocks": [
                        {
                            "kind": "stdout",
                            "title": "Agent stdout",
                            "text": text,
                            "truncated_bytes": display_truncated,
                        }
                    ],
                }

        result_was_cancelled = result.get("status") == "cancelled"
        process_was_terminated = bool(
            not outcome.timed_out
            and not outcome.output_limit_exceeded
            and outcome.returncode is not None
            and outcome.returncode < 0
        )
        completed_before_cancel = bool(
            outcome.cancelled
            and result.get("ok") is True
            and result.get("status") in {"answered", "executed"}
        )
        cancelled = bool(
            result_was_cancelled
            or (not completed_before_cancel and (outcome.cancelled or process_was_terminated))
        )
        if outcome.timed_out:
            result["ok"] = False
            result["status"] = "timed_out"
            result["error"] = f"Job exceeded its {timeout}-second runtime limit."
        elif cancelled:
            result["ok"] = False
            result["status"] = "cancelled"
            result.setdefault("error", "Job process was terminated.")

        result.setdefault(
            "ok",
            outcome.returncode == 0 and bool(result.get("ok", False)),
        )
        result.setdefault(
            "status",
            "completed" if outcome.returncode == 0 else "failed",
        )
        result["timed_out"] = bool(outcome.timed_out)
        result["cancelled"] = cancelled
        if completed_before_cancel:
            result["cancel_requested_after_completion"] = True

        blocks = result.setdefault("output_blocks", [])
        if not isinstance(blocks, list):
            blocks = []
            result["output_blocks"] = blocks
        stderr_block = cls._stderr_block(
            resource,
            outcome.stderr,
            outcome.stderr_truncated_bytes,
        )
        if stderr_block:
            blocks.append(stderr_block)
        blocks.append(
            {
                "kind": "meta",
                "title": "Agent runtime",
                "json": {
                    "exit_code": outcome.returncode,
                    "timed_out": bool(outcome.timed_out),
                    "cancelled": cancelled,
                    "cancel_requested_after_completion": completed_before_cancel,
                    "output_limit_exceeded": bool(outcome.output_limit_exceeded),
                    "stdout_truncated_bytes": outcome.stdout_truncated_bytes,
                    "stderr_truncated_bytes": outcome.stderr_truncated_bytes,
                },
            }
        )
        return result

if __name__ == "__main__":
    supervisor_exit = _run_supervisor_from_argv(sys.argv)
    if supervisor_exit is None:
        raise SystemExit("execution.py is an internal module")
    raise SystemExit(supervisor_exit)


__all__ = ["ExecutionService", "RequestContext"]
